// Generated by Copilot
// =================================================================
//                      STATE & CONFIGURATION
// =================================================================
const TABLE_CONTAINER_ID = 'requests-table-area';
const API_REQUEST_ID = 'GetRequests';
const API_DELETE_REQUEST = 'DeleteRequestID';
const API_GET_REQUEST_DETAILS = 'GetRequestID';
const API_GET_DATASET_DETAILS = 'GetDataSetID';
const API_GET_ASSIST_PROJECTS = 'GetAssistProjectsFilteredByUpn';

// We will store all fetched data here
let allRequests = []; 
let currentPage = 1;
const rowsPerPage = 5; // You can control page size here
const searchInput = document.getElementById('searchRequests');

// Mapping from Status ID to Status Name
const statusIdToNameMap = { 1: 'Pending Approval', 2: 'Approved', 3: 'Finalised', 4: 'Rejected' };

// Configuration for each status tab
const configMap = {
    'Pending Approval': { showActions: true },
    'Approved': { showActions: true },
    'Rejected': { showActions: true },
    'Finalised': { showActions: true },
};

// =================================================================
//                      UTILITY & MODAL FUNCTIONS
// =================================================================
function ViewRequest(request) {
    // Get the modal's body element
    const modalBody = document.getElementById('viewRequestModalBody');
    console.log("IN VIEW REQ")
    // Populate the modal body with the provided HTML content (your markup)
    modalBody.innerHTML = `
        <form>
            <div class="form-group">
            <label for="Name" class="control-label">Request Name</label>
            <input id="Name" class="form-control" disabled="true" value="${request.name}">
        </div>
            <div class="form-group">
                <label for="ProjectID" class="control-label">Assist Project</label>
                <select id="ProjectID" disabled="true" class="form-control selectpicker valid">
                    <option value="-1">Assist Project 1</option>
                </select>
            </div>
            <div class="form-group">
                <label for="ScheduleRefresh" class="control-label">Scheduled Refresh</label>
                <select id="ScheduleRefresh" disabled="true" class="form-control selectpicker valid">
                    <option value="No Refresh">No Refresh</option>
                    <option value="Daily">Daily</option>
                    <option value="Weekly">Weekly</option>
                    <option value="Monthly">Monthly</option>
                </select>
            </div>
            <div class="row">
                <label for="ScheduleRefresh" class="control-label">Filter's for this Data Set</label>
                <div class="table-responsive">
                    <table class="table table-condensed table-striped">
                        <thead>
                            <tr>
                                <th>Column</th>
                                <th>Filter Type</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Example of empty table body; data can be populated later -->
                            <tr>
                                <td colspan="3">No filters available.</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    `;

}

async function ViewDataSet(request) {
    return new Promise(async (resolve, reject) => {
        try {
            // You can still update the modal if needed
            const modalBody = document.getElementById('viewDatasetModalBody');
            
            // Fetch dataset details - replace this with your actual data fetching logic
            // This could be an API call, database query, etc.
            const datasetDetails = await fetchDatasetDetails(request.DataSetID);
            
            // If you still want to update the modal
            if (modalBody) {
                // Format the dataset details for the modal
                let modalContent = `
                    <div class="form-group">
                        <label for="DataSetType" class="form-check-label">Data Source</label>
                        <select disabled="true" class="form-control selectpicker valid">
                            <option value="1" ${datasetDetails.DataSourceID === 1 ? 'selected' : ''}>BIS Data (pilot test)</option>
                            <option value="4" ${datasetDetails.DataSourceID === 4 ? 'selected' : ''}>Barwon Health DB Source View 1</option>
                            <option value="25" ${datasetDetails.DataSourceID === 25 ? 'selected' : ''}>Source Mock SQL Data for Testing</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <div class="form-check">
                            <input id="Active" disabled="true" type="checkbox" class="form-check-input valid" ${datasetDetails.Active ? 'checked' : ''}>
                            <label for="Active" class="form-check-label">Active</label>
                        </div>
                    </div>
                    <br>
                    <h6>Data Set Fields</h6>
                    <div class="table-responsive">
                        <table class="table table-condensed table-striped">
                            <thead>
                                <tr>
                                    <th>Field Name</th>
                                    <th>Type</th>
                                    <th>Description</th>
                                </tr>
                            </thead>
                            <tbody>
                `;
                
                // Add dataset fields to the modal
                if (datasetDetails.Fields && datasetDetails.Fields.length > 0) {
                    datasetDetails.Fields.forEach(field => {
                        modalContent += `
                            <tr>
                                <td>${field.Name}</td>
                                <td>${field.Type}</td>
                                <td>${field.Description || ''}</td>
                            </tr>
                        `;
                    });
                } else {
                    modalContent += `<tr><td colspan="3" class="text-center">No fields available</td></tr>`;
                }
                
                modalContent += `
                            </tbody>
                        </table>
                    </div>
                `;
                
                modalBody.innerHTML = modalContent;
            }
            
            // Format the dataset details for the accordion
            const formattedDetails = {
                DataSetID: datasetDetails.DataSetID,
                Name: datasetDetails.Name,
                Description: datasetDetails.Description || 'No description available',
                DataSource: getDataSourceName(datasetDetails.DataSourceID),
                Active: datasetDetails.Active ? 'Yes' : 'No',
                CreatedDate: formatDate(datasetDetails.CreatedDate),
                LastModified: formatDate(datasetDetails.LastModified),
                FieldCount: datasetDetails.Fields ? datasetDetails.Fields.length : 0,
                Fields: formatFieldsForAccordion(datasetDetails.Fields)
            };
            
            // Resolve the promise with the formatted details
            resolve(formattedDetails);
            
        } catch (error) {
            console.error('Error fetching dataset details:', error);
            reject(error);
        }
    });
}

// Helper function to get data source name from ID
function getDataSourceName(dataSourceID) {
    const dataSources = {
        1: 'BIS Data (pilot test)',
        4: 'Barwon Health DB Source View 1',
        25: 'Source Mock SQL Data for Testing'
    };
    return dataSources[dataSourceID] || `Unknown Source (${dataSourceID})`;
}

// Helper function to format fields for the accordion
function formatFieldsForAccordion(fields) {
    if (!fields || fields.length === 0) {
        return 'No fields available';
    }
    
    let fieldsHtml = '<div class="mt-2"><table class="w-full text-sm"><thead><tr><th class="text-left">Field</th><th class="text-left">Type</th></tr></thead><tbody>';
    
    fields.forEach(field => {
        fieldsHtml += `<tr><td>${field.Name}</td><td>${field.Type}</td></tr>`;
    });
    
    fieldsHtml += '</tbody></table></div>';
    return fieldsHtml;
}


// =================================================================
// Miguel
function DeleteRequest(request) {
    // Get the modal elements
    const modalBody = document.getElementById('deleteRequestModalBody');
    const modalTitle = document.getElementById('deleteRequestModalLabel');
    
    // Update the modal title
    modalTitle.textContent = `Delete Request`;
    
    // Populate the modal body with the confirmation message
    modalBody.innerHTML = `
        <div class="col-md-12">
            <div class="alert alert-warning">
                <i class="fa fa-exclamation-triangle"></i> 
                You are about to delete the request:<br>
                <strong>${request.Name}</strong>
            </div>
            <div class="form-group mt-3 d-flex justify-content-center">
                <button id="confirmDeleteBtn" class="btn btn-danger px-3 py-1">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 inline mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                    </svg>
                    Delete
                </button>
            </div>
        </div>
    `;
    
    // Add event listener for the confirm delete button
    setTimeout(() => {
        const confirmBtn = document.getElementById('confirmDeleteBtn');
        if (confirmBtn) {
            console.log('Adding click listener to confirm delete button');
            confirmBtn.addEventListener('click', () => {
                console.log('Delete button clicked for request:', request.RequestID);
                // Call the API to delete the request
                deleteRequestFromAPI(request.RequestID);
            });
        } else {
            console.error('Confirm delete button not found');
        }
    }, 100);
}

async function deleteRequestFromAPI(requestId) {
    let loadingToast = null;
    
    try {
        console.log('Starting delete request process for ID:', requestId);
        
        // Show loading state
        loadingToast = showToast('Deleting request...', 'info');
        console.log('Loading toast shown:', loadingToast);
        
        const response = await window.loomeApi.runApiRequest(API_DELETE_REQUEST, {
            "id": requestId,
        });
        
        // Log the response to console
        console.log('Delete request API response:', response);
        
        // Hide the modal
        try {
            const deleteModal = bootstrap.Modal.getInstance(document.getElementById('deleteRequestModal'));
            if (deleteModal) {
                deleteModal.hide();
                console.log('Delete modal hidden');
            } else {
                console.log('Delete modal not found or already hidden');
            }
        } catch (modalError) {
            console.error('Error hiding modal:', modalError);
        }
        
        // Hide loading toast
        if (loadingToast) {
            hideToast(loadingToast);
            console.log('Loading toast hidden');
        }
        
        // Show success message
        const successToast = showToast('Request deleted successfully', 'success');
        console.log('Success toast shown:', successToast);
        
        // Update all chip counts after deletion
        console.log('Refreshing chip counts');
        await refreshAllChipCounts();

        // Refresh the UI
        console.log('Refreshing UI');
        setTimeout(() => {
            renderUI();
        }, 100);
        
    } catch (error) {
        console.error("Error deleting request:", error);
        
        // Hide loading toast
        if (loadingToast) {
            hideToast(loadingToast);
            console.log('Loading toast hidden after error');
        }
        
        // Show error message
        const errorToast = showToast('Failed to delete request. Please try again.', 'error');
        console.log('Error toast shown:', errorToast);
    }
}

// Toast notification functions
function showToast(message, type = 'info') {
    const toastContainer = document.getElementById('toast-container') || createToastContainer();
    const toast = document.createElement('div');
    toast.className = `toast-item toast-${type}`;
    toast.style.cssText = 'margin-bottom:0;padding:12px 16px;border-radius:6px;color:#fff;display:flex;align-items:center;min-width:250px;max-width:360px;opacity:0;transform:translateY(-6px);transition:opacity .2s ease,transform .2s ease;';

    let bg = '#2196F3';
    if (type === 'success') bg = '#1AABA3';
    if (type === 'error') bg = '#f44336';
    if (type === 'warning') bg = '#ff9800';
    toast.style.backgroundColor = bg;

    const text = document.createElement('div');
    text.style.flex = '1';
    text.textContent = message;
    toast.appendChild(text);

    if (type === 'error') {
        const btn = document.createElement('button');
        btn.innerHTML = '&times;';
        btn.style.cssText = 'background:transparent;border:none;color:#fff;font-size:18px;margin-left:12px;cursor:pointer;';
        btn.onclick = () => { if (toast.parentNode) toast.remove(); };
        toast.appendChild(btn);
    }

    toastContainer.appendChild(toast);
    requestAnimationFrame(() => { toast.style.opacity = '1'; toast.style.transform = 'translateY(0)'; });

    if (type !== 'error') {
        setTimeout(() => { if (toast.parentNode) { toast.style.opacity = '0'; setTimeout(() => toast.remove(), 200); } }, 5000);
    }

    return toast;
}

function hideToast(toast) {
    if (toast && toast.parentNode) {
        console.log('Hiding toast');
        toast.style.opacity = '0';
        setTimeout(() => {
            if (toast && toast.parentNode) {
                toast.remove();
                console.log('Toast removed');
            }
        }, 300); // Wait for fade out
    } else {
        console.log('Toast not found or already removed');
    }
}

function createToastContainer() {
    const container = document.createElement('div');
    container.id = 'toast-container';
    container.className = 'toast-top-right';
    container.style.cssText = 'position: fixed; top: 12px; right: 12px; z-index: 9999;';
    document.body.appendChild(container);
    return container;
}


/**
 * Fetches request details from the API
 * @param {string|number} requestID - The ID of the request
 * @returns {Promise<object>} - The request details
 */
async function fetchRequestDetails(requestID) {
    try {
        // Call the API
        const response = await window.loomeApi.runApiRequest(API_GET_REQUEST_DETAILS, {
            "RequestID": requestID,
        });
        
        // Parse the response
        return safeParseJson(response);
    } catch (error) {
        console.error(`Error fetching request details for ID ${requestID}:`, error);
        throw error;
    }
}

/**
 * Fetches dataset details from the API
 * @param {string|number} datasetID - The ID of the dataset
 * @returns {Promise<object>} - The dataset details
 */
async function fetchDatasetDetails(datasetID) {
    try {
        // Call the API
        const response = await window.loomeApi.runApiRequest(API_GET_DATASET_DETAILS, {
            "DataSetID": datasetID,
        });
        
        // Parse the response
        return safeParseJson(response);
    } catch (error) {
        console.error(`Error fetching dataset details for ID ${datasetID}:`, error);
        throw error;
    }
}



// Global variable to store project data
let projectsCache = null;

/**
 * Fetches all projects and caches them
 * @returns {Promise<Object>} A mapping from project ID to project name
 */
async function getProjectsMapping() {
    // Return cache if already loaded
    if (projectsCache) {
        return projectsCache;
    }
    
    try {
        
        // Fetch projects data
        const response = await window.loomeApi.runApiRequest(API_GET_ASSIST_PROJECTS);
        const data = safeParseJson(response);
        
        // Create a mapping from project ID to project name
        const mapping = {};
        if (data && data.Results && Array.isArray(data.Results)) {
            data.Results.forEach(project => {
                mapping[project.AssistProjectID] = {
                    name: project.Name,
                    description: project.Description
                };
            });
        }
        
        // Cache the mapping
        projectsCache = mapping;
        return mapping;
        
    } catch (error) {
        console.error("Error fetching projects:", error);
        return {}; // Return empty object in case of error
    }
}


/**
 * Displays request details in the container
 * @param {HTMLElement} container - The container element
 * @param {object} details - The request details
 */
async function displayRequestDetails(container, details) {
    // Check if we have valid details
    if (!details || Object.keys(details).length === 0) {
        container.innerHTML = '<p class="text-center text-red-500">No request details available</p>';
        return;
    }
    
    // Show loading state
    container.innerHTML = '<p class="text-center">Loading project details...</p>';
    
    try {
        // Get project mapping
        const projectsMapping = await getProjectsMapping();
        const projectInfo = projectsMapping[details.ProjectID] || { name: 'Unknown Project', description: '' };
        
        // Format the details for display
        let html = '';
        
        // Add basic request information
        html += `
            <p><strong>Target Project Name:</strong> ${projectInfo.name}</p>
        `;
        
        // Add project description if available
        if (projectInfo.description) {
            html += `<p><strong>Project Description:</strong> ${projectInfo.description}</p>`;
        }
        
        // // Add status-specific fields
        // if (details.Approvers) html += `<p><strong>Approvers:</strong> ${details.Approvers}</p>`;
        // if (details.ApprovedBy) html += `<p><strong>Approved By:</strong> ${details.ApprovedBy}</p>`;
        // if (details.ApprovedDate) html += `<p><strong>Approved Date:</strong> ${formatDate(details.ApprovedDate)}</p>`;
        // if (details.RejectedBy) html += `<p><strong>Rejected By:</strong> ${details.RejectedBy}</p>`;
        // if (details.RejectedDate) html += `<p><strong>Rejected Date:</strong> ${formatDate(details.RejectedDate)}</p>`;
        // if (details.FinalisedDate) html += `<p><strong>Finalised Date:</strong> ${formatDate(details.FinalisedDate)}</p>`;
        
        // // Add any additional fields from the API response
        // const standardFields = ['RequestID', 'ProjectID', 'Name', 'Description', 'CreateDate', 'Status', 
        //                       'Approvers', 'ApprovedBy', 'ApprovedDate', 'RejectedBy', 
        //                       'RejectedDate', 'FinalisedDate'];
        
        // for (const [key, value] of Object.entries(details)) {
        //     if (!standardFields.includes(key) && value !== null && value !== undefined) {
        //         html += `<p><strong>${key}:</strong> ${value}</p>`;
        //     }
        // }
        
        // Update the container
        container.innerHTML = html;
        
    } catch (error) {
        console.error("Error displaying request details:", error);
        container.innerHTML = `
            <p class="text-center text-red-500">Error loading project details</p>
            <div class="mt-3">
                <p><strong>Request ID:</strong> ${details.RequestID || 'N/A'}</p>
                <p><strong>Name:</strong> ${details.Name || 'N/A'}</p>
                <p><strong>Project ID:</strong> ${details.ProjectID || 'N/A'}</p>
                <p><strong>Status:</strong> ${details.Status || 'Unknown'}</p>
                <!-- Add other critical fields here -->
            </div>
        `;
    }
}

/**
 * Displays dataset details in the container
 * @param {HTMLElement} container - The container element
 * @param {object} details - The dataset details
 */
function displayDatasetDetails(container, details) {
    // Check if we have valid details
    if (!details || Object.keys(details).length === 0) {
        container.innerHTML = '<p class="text-center text-red-500">No dataset details available</p>';
        return;
    }
    
    // Format the details for display
    let html = '';
    
    // Add basic dataset information
    html += `
        <p><strong>Requested Dataset:</strong> ${details.Name || 'N/A'}</p>
        <p><strong>Description:</strong> ${details.Description || 'N/A'}</p>
        <p><strong>Data Source ID:</strong> ${details.DataSourceID || 'N/A'}</p>
    `;
    
    // Add fields table if available
    if (details.Fields && details.Fields.length > 0) {
        html += `
            <div class="mt-3">
                <strong>Fields:</strong>
                <div class="mt-2">
                    <table class="w-full text-sm">
                        <thead>
                            <tr>
                                <th class="text-left">Field</th>
                                <th class="text-left">Type</th>
                                <th class="text-left">Description</th>
                            </tr>
                        </thead>
                        <tbody>
        `;
        
        details.Fields.forEach(field => {
            html += `
                <tr>
                    <td>${field.Name || 'N/A'}</td>
                    <td>${field.Type || 'N/A'}</td>
                    <td>${field.Description || ''}</td>
                </tr>
            `;
        });
        
        html += `
                        </tbody>
                    </table>
                </div>
            </div>
        `;
    }
    
    // Update the container
    container.innerHTML = html;
}
// =================================================================


/**
 * Displays combined request and dataset details in a single container
 * @param {HTMLElement} container - The container element
 * @param {object} requestDetails - The request details
 * @param {object} datasetDetails - The dataset details
 */
async function displayCombinedDetails(container, requestDetails, datasetDetails) {
    // Check if we have valid details
    if ((!requestDetails || Object.keys(requestDetails).length === 0) && 
        (!datasetDetails || Object.keys(datasetDetails).length === 0)) {
        container.innerHTML = '<p class="text-center text-red-500">No details available</p>';
        return;
    }
    
    // Show loading state
    container.innerHTML = '<p class="text-center">Loading details...</p>';
    
    try {
        // Get project mapping for request details
        const projectsMapping = await getProjectsMapping();
        const projectInfo = requestDetails && requestDetails.ProjectID ? 
            (projectsMapping[requestDetails.ProjectID] || { name: 'Unknown Project', description: '' }) : 
            { name: 'Unknown Project', description: '' };
        
        // Start building HTML
        let html = `
            <div class="grid grid-cols-1 gap-5">
                <!-- Request Information -->
                <div>
                    <div class="space-y-3">
                       
                        <!-- Dataset Information -->
                        <div class="grid grid-cols-1 gap-1">
                            <span class="font-medium">Requested Dataset</span>
                            <span class="text-sm text-gray-500">${datasetDetails.Name || 'N/A'}</span>
                        </div>

                        ${datasetDetails.Description ? `
                        <div class="grid grid-cols-1 gap-1">
                            <span class="font-medium">Dataset Description</span>
                            <span class="text-sm text-gray-500">${datasetDetails.Description}</span>
                        </div>` : ''}
                        
                        <div class="grid grid-cols-1 gap-1">
                            <span class="font-medium">Data Source ID</span>
                            <span class="text-sm text-gray-500">${datasetDetails.DataSource || datasetDetails.DataSourceID || 'N/A'}</span>
                        </div>

                        <!-- Project Information -->
                        <div class="grid grid-cols-1 gap-1">
                            <span class="font-medium">Target Project Name</span>
                            <span class="text-sm text-gray-500">${projectInfo.name}</span>
                        </div>
                        
                        ${projectInfo.description ? `
                        <div class="grid grid-cols-1 gap-1">
                            <span class="font-medium">Project Description</span>
                            <span class="text-sm text-gray-500">${projectInfo.description}</span>
                        </div>` : ''}

                    </div>
                </div>
            </div>
        `;
        
        // Update the container
        container.innerHTML = html;
        
    } catch (error) {
        console.error("Error displaying combined details:", error);
        container.innerHTML = `
            <div class="p-3 bg-red-50 border border-red-200 rounded-md">
                <p class="text-center text-red-500 mb-2">Error loading details</p>
                <p class="text-sm">${error.message || 'Unknown error'}</p>
            </div>
        `;
    }
}


/**
 * Safely parses a response that might be a JSON string or an object.
 * @param {string | object} response The API response.
 * @returns {object}
 */
function safeParseJson(response) {
    return typeof response === 'string' ? JSON.parse(response) : response;
}

/**
* Renders a compact and functional set of pagination controls.
* Includes First, Previous, Next, Last buttons and a page input field.
*/
function renderPagination(containerId, totalItems, itemsPerPage, currentPage) {
    const container = document.getElementById(containerId);
    if (!container) {
        console.error(`Pagination container with ID "${containerId}" not found.`);
        return;
    }

    const totalPages = Math.ceil(totalItems / itemsPerPage);
    container.innerHTML = ''; // Clear old controls

    if (totalPages <= 1) {
        return; // No need for pagination.
    }

    // --- Determine button states ---
    const isFirstPage = currentPage === 1;
    const isLastPage = currentPage === totalPages;
    const commonButtonClasses = "px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-100";
    const disabledClasses = "opacity-50 cursor-not-allowed";

    // --- Build the HTML string ---
    let paginationHTML = `
        <div class="flex items-center gap-2">
            <!-- First Page Button -->
            <button data-page="1" 
                    class="${commonButtonClasses} ${isFirstPage ? disabledClasses : ''}" 
                    ${isFirstPage ? 'disabled' : ''}>
                First
            </button>
            <!-- Previous Page Button -->
            <button data-page="${currentPage - 1}" 
                    class="${commonButtonClasses} ${isFirstPage ? disabledClasses : ''}" 
                    ${isFirstPage ? 'disabled' : ''}>
                Previous
            </button>
        </div>

        <!-- Page number input and display -->
        <div class="flex items-center gap-2 text-sm text-gray-700">
            <span>Page</span>
            <input type="number" 
                   id="page-input" 
                   class="w-16 text-center border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" 
                   value="${currentPage}" 
                   min="1" 
                   max="${totalPages}" 
                   aria-label="Current page">
            <span>of ${totalPages}</span>
        </div>

        <div class="flex items-center gap-2">
            <!-- Next Page Button -->
            <button data-page="${currentPage + 1}" 
                    class="${commonButtonClasses} ${isLastPage ? disabledClasses : ''}" 
                    ${isLastPage ? 'disabled' : ''}>
                Next
            </button>
            <!-- Last Page Button -->
            <button data-page="${totalPages}" 
                    class="${commonButtonClasses} ${isLastPage ? disabledClasses : ''}" 
                    ${isLastPage ? 'disabled' : ''}>
                Last
            </button>
        </div>
    `;

    container.innerHTML = paginationHTML;
}

function formatDate(inputDate) {
    // Log what the function receives
    console.log(`formatDate received:`, inputDate, `(type: ${typeof inputDate})`);

    if (!inputDate) {
        // This will be triggered if inputDate is null, undefined, or an empty string ""
        return 'N/A'; 
    }

    const date = new Date(inputDate);
    
    if (isNaN(date.getTime())) {
        // This will be triggered if the date string is invalid, e.g., "hello world"
        console.warn(`Could not parse invalid date:`, inputDate);
        return 'N/A';
    }
    
    const formattingOptions = {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    };
    
    // The only way this returns undefined is if the function exits before this line.
    return date.toLocaleDateString('en-US', formattingOptions);
}


// =================================================================
//                      API & RENDERING FUNCTIONS
// =================================================================


/**
 * Renders a data table with dynamic headers and actions.
 */
function renderTable(containerId, data, config, selectedStatus) {
    const container = document.getElementById(containerId);
    container.innerHTML = '';
    const table = document.createElement('table');
    table.className = 'w-full divide-y divide-gray-200';
    const thead = document.createElement('thead');
    thead.className = 'bg-gray-50';
    const headerRow = document.createElement('tr');
    
    // Add a column for the chevron
    const chevronTh = document.createElement('th');
    chevronTh.className = 'w-10 px-6 py-3';
    chevronTh.innerHTML = ''; // Empty header for chevron column
    headerRow.appendChild(chevronTh);
    
    // Define headers based on the selected status
    const headers = ['Request ID', 'Request Name', 'Requested On'];
    if (selectedStatus === 'Pending Approval') headers.push('Approvers');
    else if (selectedStatus === 'Approved') { headers.push('Approved by'); headers.push('Approved on'); }
    else if (selectedStatus === 'Rejected') { headers.push('Rejected by'); headers.push('Rejected on'); }
    else if (selectedStatus === 'Finalised') { headers.push('Approved by'); headers.push('Approved on'); headers.push('Finalised on'); }
            
    
    headers.forEach(headerText => {
        const th = document.createElement('th');
        th.className = 'px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider';
        th.textContent = headerText;
        headerRow.appendChild(th);
    });
    thead.appendChild(headerRow);
    table.appendChild(thead);
    
    const tbody = document.createElement('tbody');
    tbody.className = 'bg-white divide-y divide-gray-200';
    
    if (data.length === 0) {
        const colSpan = headers.length + 1; // +1 for chevron column
        tbody.innerHTML = `<tr><td colspan="${colSpan}" class="px-6 py-4 text-center text-sm text-gray-500">No requests found.</td></tr>`;
    } else {
        data.forEach(item => {
            const row = document.createElement('tr');
            row.className = 'cursor-pointer hover:bg-gray-100';
            const tdClasses = 'px-6 py-4 whitespace-nowrap text-sm text-gray-800';
            
            let statusSpecificCols = '';
            switch (item.status) {
                case 'Pending Approval': statusSpecificCols = `<td class="${tdClasses}">${item.Approvers || 'N/A'}</td>`; break;
                case 'Rejected': statusSpecificCols = `<td class="${tdClasses}">${item.RejectedBy || 'N/A'}</td><td class="${tdClasses}">${formatDate(item.RejectedDate)}</td>`; break;
                case 'Approved': statusSpecificCols = `<td class="${tdClasses}">${item.CurrentlyApproved || 'N/A'}</td><td class="${tdClasses}">${formatDate(item.ApprovedDate)}</td>`; break;
                case 'Finalised': statusSpecificCols = `<td class="${tdClasses}">${item.CurrentlyApproved || 'N/A'}</td><td class="${tdClasses}">${formatDate(item.ApprovedDate)}</td><td class="${tdClasses}">${formatDate(item.FinalisedDate)}</td>`; break;
            }

            // Add chevron as first column
            row.innerHTML = `
                <td class="${tdClasses} text-center">
                    <svg class="chevron-icon h-5 w-5 text-gray-500 transform transition-transform duration-200 inline-block" 
                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                    </svg>
                </td>
                <td class="${tdClasses}">${item.RequestID}</td>
                <td class="${tdClasses}">${item.Name}</td>
                <td class="${tdClasses}">${formatDate(item.CreateDate)}</td>
                ${statusSpecificCols}
            `;
            
            // Add click event to toggle accordion
            row.addEventListener('click', async () => {
                // Toggle the accordion visibility
                accordionRow.classList.toggle('hidden');
                
                // Toggle chevron rotation
                const chevron = row.querySelector('.chevron-icon');
                chevron.classList.toggle('rotate-180');
                
                // Only fetch data if the accordion is becoming visible
                if (!accordionRow.classList.contains('hidden')) {
                    const combinedDetailsContainer = accordionRow.querySelector(`#combined-details-${item.RequestID}`);
                    
                    // Show loading indicator
                    combinedDetailsContainer.innerHTML = '<p class="text-center">Loading details...</p>';
                    
                    try {
                        console.log(`Fetching details for RequestID: ${item.RequestID}, DataSetID: ${item.DataSetID}`);
                        
                        // Try fetching request details first
                        let requestDetails;
                        try {
                            console.log('Fetching request details...');
                            requestDetails = await fetchRequestDetails(item.RequestID);
                            console.log('Request details received:', requestDetails);
                        } catch (requestError) {
                            console.error('Error fetching request details:', requestError);
                            requestDetails = null;
                        }
                        
                        // Then try fetching dataset details
                        let datasetDetails;
                        try {
                            console.log('Fetching dataset details...');
                            datasetDetails = await fetchDatasetDetails(item.DataSetID);
                            console.log('Dataset details received:', datasetDetails);
                        } catch (datasetError) {
                            console.error('Error fetching dataset details:', datasetError);
                            datasetDetails = null;
                        }
                        
                        // Check if we have at least one set of details
                        if (!requestDetails && !datasetDetails) {
                            throw new Error('Failed to fetch both request and dataset details');
                        }
                        
                        // Display whatever details we have
                        console.log('Displaying combined details');
                        displayCombinedDetails(combinedDetailsContainer, requestDetails, datasetDetails);
                        
                    } catch (error) {
                        console.error("Error loading details:", error);
                        combinedDetailsContainer.innerHTML = `
                            <div class="p-3 bg-red-50 border border-red-200 rounded-md">
                                <p class="text-center text-red-500 mb-2">Error loading details</p>
                                <p class="text-sm">${error.message || 'Unknown error'}</p>
                                <button class="mt-2 px-3 py-1 bg-white border border-gray-300 rounded text-sm retry-btn">
                                    Retry
                                </button>
                            </div>
                        `;
                        
                        // Add retry button functionality
                        combinedDetailsContainer.querySelector('.retry-btn')?.addEventListener('click', async (e) => {
                            e.stopPropagation();
                            combinedDetailsContainer.innerHTML = '<p class="text-center">Loading details...</p>';
                            try {
                                const retryRequestDetails = await fetchRequestDetails(item.RequestID);
                                const retryDatasetDetails = await fetchDatasetDetails(item.DataSetID);
                                displayCombinedDetails(combinedDetailsContainer, retryRequestDetails, retryDatasetDetails);
                            } catch (retryError) {
                                combinedDetailsContainer.innerHTML = `
                                    <div class="p-3 bg-red-50 border border-red-200 rounded-md">
                                        <p class="text-red-600">Failed to load details</p>
                                        <p class="text-sm text-red-500 mt-1">${retryError.message || 'Unknown error'}</p>
                                    </div>
                                `;
                            }
                        });
                    }
                }
            });
            
            // Create accordion row
            const accordionRow = document.createElement('tr');
            accordionRow.classList.add('hidden', 'accordion-row');
            if (selectedStatus === 'Pending Approval') {
                accordionRow.innerHTML = `
                    <td colspan="${headers.length + 1}" class="p-0"> <!-- +1 for chevron column -->
                        <div class="bg-gray-50 p-4 m-2 rounded">
                            <div class="grid grid-cols-1 gap-4">
                                <div class="flex justify-end mb-1">
                                    <button class="btn btn-danger action-delete px-3 py-1" data-bs-toggle="modal" data-bs-target="#deleteRequestModal">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 inline mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                        </svg>
                                        Delete
                                    </button>
                                </div>
                                
                                <!-- Combined Information Card -->
                                <div class="bg-white p-5 rounded-md shadow-sm">
                                    <div id="combined-details-${item.RequestID}" class="combined-content">
                                        <p class="text-center text-gray-500">Loading details...</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                `;
            } else {
                accordionRow.innerHTML = `
                    <td colspan="${headers.length + 1}" class="p-0"> <!-- +1 for chevron column -->
                        <div class="bg-gray-50 p-4 m-2 rounded">
                            <div class="grid grid-cols-1 gap-4">                            
                                <!-- Combined Information Card -->
                                <div class="bg-white p-5 rounded-md shadow-sm">
                                    <div id="combined-details-${item.RequestID}" class="combined-content">
                                        <p class="text-center text-gray-500">Loading details...</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                `;
            }

            
            // Add event listeners for the accordion
            const loadDatasetBtn = accordionRow.querySelector('.load-dataset-details');
            const deleteBtn = accordionRow.querySelector('.action-delete');
            loadDatasetBtn?.addEventListener('click', async (e) => {
                e.stopPropagation();
                // Your existing code for loading dataset details...
            });
            deleteBtn?.addEventListener('click', (e) => {
                e.stopPropagation();
                DeleteRequest(item);
            });
            tbody.appendChild(row);
            tbody.appendChild(accordionRow);
        });
    }
    
    table.appendChild(tbody);
    container.appendChild(table);
    
    // Add this style to your CSS or inline here
    const style = document.createElement('style');
    style.textContent = `
        .rotate-180 {
            transform: rotate(180deg);
        }
        .transition-transform {
            transition: transform 0.2s;
        }
    `;
    document.head.appendChild(style);
}


// =================================================================
//                     PRIMARY RENDER FUNCTION
// =================================================================

async function getCounts(status) {
    const apiParams = {
        "page": currentPage,
        "pageSize": rowsPerPage,
        "search": '',
        "statusId": parseInt(Object.keys(statusIdToNameMap).find(key => statusIdToNameMap[key] === status))
    }
    
    console.log(apiParams)
    const response = await window.loomeApi.runApiRequest(API_REQUEST_ID, apiParams);
    const parsedResponse = safeParseJson(response);

    return parsedResponse.RowCount;
}

// Add this function to refresh all chip counts
async function refreshAllChipCounts() {
    const chipsContainer = document.getElementById('status-chips-container');
    for (const chip of chipsContainer.querySelectorAll('.chip')) {
        const status = chip.dataset.status;
        const count = await getCounts(status);
        chip.querySelector('.chip-count').textContent = count;
    }
}

/**
 * Main function to orchestrate all rendering based on the current state.
 * It filters, paginates, and renders the table and controls.
 */
async function renderUI() {
    const activeChip = document.querySelector('.chip.active');
    if (!activeChip) return; // Don't render if no chip is active
    
    const selectedStatus = activeChip.dataset.status;
    const searchTerm = searchInput.value.toLowerCase();

    // --- 1. FETCH ALL DATA ONCE ---
    // We call the API without pagination params, assuming it returns all records.
    // If your API requires pagination, you'd need to fetch all pages in a loop here.
    const apiParams = {
        "page": currentPage,
        "pageSize": rowsPerPage,
        "search": searchTerm,
        "statusId": parseInt(Object.keys(statusIdToNameMap).find(key => statusIdToNameMap[key] === selectedStatus))
    }
    
    console.log(apiParams)
    const response = await window.loomeApi.runApiRequest(API_REQUEST_ID, apiParams);
    const parsedResponse = safeParseJson(response)
    const rawData = parsedResponse.Results;
    const totalItems = parsedResponse.RowCount;
    console.log(rawData)

    // --- 2. PREPARE THE MASTER DATA ARRAY ---
    // Transform the raw data just once into the format our UI needs.
    allRequests = rawData.map(item => ({
        ...item,
        status: statusIdToNameMap[item.StatusID] || 'Unknown'
    }));
    console.log(allRequests)

    // --- Render the components ---
    const configForTable = configMap[selectedStatus];
    renderTable(TABLE_CONTAINER_ID, allRequests, configForTable, selectedStatus);
    renderPagination('pagination-controls', totalItems, rowsPerPage, currentPage);
}

// =================================================================
//                      INITIALIZATION
// =================================================================

/**
 * Main function to initialize the page, fetch all data, and set up listeners.
 */
async function renderMyRequestsPage() {
    try {

        // --- 3. UPDATE ALL CHIP COUNTS ONCE ---
        // This is the logic you wanted. It calculates counts from the unfiltered master array.
        const chipsContainer = document.getElementById('status-chips-container');
        for (const chip of chipsContainer.querySelectorAll('.chip')) {
            const status = chip.dataset.status;
            console.log(status)
            // Await the asynchronous getCounts function for each chip
            const count = await getCounts(status);
            chip.querySelector('.chip-count').textContent = count;
        }

        // --- 4. SETUP EVENT LISTENERS ---
        
        // Listener for status chip clicks
        chipsContainer.addEventListener('click', (event) => {
            const clickedChip = event.target.closest('.chip');
            if (!clickedChip) return;

            chipsContainer.querySelectorAll('.chip').forEach(chip => chip.classList.remove('active'));
            clickedChip.classList.add('active');
            
            currentPage = 1; // Reset to page 1 when changing tabs
            renderUI(); // Re-render everything
        });

        // Listener for the search input
        searchInput.addEventListener('input', () => {
            currentPage = 1; // Reset to page 1 when searching
            renderUI(); // Re-render everything
        });

        // Listener for pagination controls
        const paginationContainer = document.getElementById('pagination-controls');
        
        // Handle button clicks
        paginationContainer.addEventListener('click', (event) => {
            const button = event.target.closest('button[data-page]');
            if (!button || button.disabled) return;
            
            currentPage = parseInt(button.dataset.page, 10);
            renderUI(); // Re-render everything
        });

        // Handle page input
        paginationContainer.addEventListener('keydown', (event) => {
            // Only act if the user pressed Enter and the target is our input
            if (event.key === 'Enter' && event.target.id === 'page-input') {
                const newPage = parseInt(event.target.value, 10);
                if (!isNaN(newPage) && newPage > 0) {
                    currentPage = newPage;
                    renderUI();
                }
            }
        });

        // --- 5. INITIAL PAGE RENDER ---
        // Programmatically click the first chip to trigger the initial render.
        document.querySelector('.chip[data-status="Pending Approval"]').click();

    } catch (error) {
        console.error("Error setting up the page:", error);
        // ... your error handling ...
    }
}

// Start the application
renderMyRequestsPage();
